version: '3.4'

services:
  mariadb:
    image: mariadb
    build:
      context: .
      dockerfile: sql/Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - "/var/lib/mysql:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD:admin

  api:
    image: cart/cart-api
    build:
      context: .
      dockerfile: src/Cart/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Compose
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:80"
    depends_on:
      - silo

  silo:
    image: cart/cart-silo
    build:
      context: .
      dockerfile: src/Silo/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Compose
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5001:80"
      - "11111:11111"
      - "30000:30000"
    depends_on:
      - mariadb
