http://localhost:5000
GET /api/cart/aedc275d-4a41-41f0-851a-5423217a9429

//POST /api/cart/aedc275d-4a41-41f0-851a-5423217a9429/product
//{
//	"productId": 2,
//	"productPrice": 2.33,
//	"productDescription": "Test product"
//}
